### ISSUE TITLE
Picker doesn't work

### ISSUE THREAD

**Issue by delverdev** [mistic100/angular-smilies#12]
Input-addon appears, but tooltip doesn't. Smilies work.
angular 1.5.5
angular-bootstrap 1.3.3

```html
<form class="input-group m-t-10" ng-if="vm.isAuthenticated()" ng-submit="chatVm.sendMessage()">
            <span class="input-group-addon" smilies-selector="chatVm.message" smilies-placement="right" smilies-title="Smilies"></span>
            <input type="text" class="form-control chat-input" minlength="1" maxlength="100" placeholder="Enter your text" ng-model="chatVm.message" focus-on-change="chatVm.message">
            <span class="input-group-btn">
                <button type="submit" class="btn btn-primary waves-effect waves-light"><i class="fa fa-send-o"></i></button>
            </span>
</form>
```

**Comment by mistic100** [comment]
Do you have AngularUI or Angular Strap ?

Please create an online demo of the problem.

**Comment by delverdev** [comment]
I can't create plunker or fiddle because cannot add a sprite image. I use angular-bootstrap. Or I have to connected anything else?

**Comment by mistic100** [comment]
Of course you can add a sprite ! just overwite the CSS

```css
[class^='smiley-'], [class*=' smiley-'] {
background-image:url('https://cdn.rawgit.com/mistic100/angular-smilies/master/dist/angular-smilies.png');
}
```

https://github.com/mistic100/angular-smilies/blob/master/dist/angular-smilies-embed.min.css
