### ISSUE TITLE
Missing display: inline-block

### ISSUE THREAD

**Issue by Devqon** [mistic100/angular-smilies#3]
I tried to use this library, but the smilies didn't appear. After an hour digging I found out that in the example the `[class^='smiley-'], [class*=' smiley-']` had a display inline-block, that was missing in the angular-smilies.css:

```css
[class^='smiley-'], [class*=' smiley-'] {
    display: inline-block; /* <-- this was missing */
    background-image:url('angular-smilies.png'); 
    width:18px; 
    height:18px; 
}
```
